# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts v3.0.0
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.3.0
  - Desiigner07/solidity-lib@2.1.0
  - Desiigner07/v2-core@1.0.1

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.6.6
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.3.0"
      - "@uniswap/lib=Desiigner07/solidity-lib@2.1.0"
      - "@uniswap/v2-core=Desiigner07/v2-core@1.0.1"
networks:
  default: mainnet-fork
  mainnet-fork:
  kovan:
  mainnet:
  bsc-main: 
  bsc-test: 

wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}
